[profile.default]

libs = ['lib']

remappings = [
  '@openzeppelin/=lib/openzeppelin-contracts/'
]
solc_version = '0.8.10'
src = 'contracts'
test = 'test'

# See more config options https://github.com/foundry-rs/foundry/tree/master/config